### ISSUE TITLE
Issue with logic for current status

### ISSUE THREAD

**Issue by rsmaior** [oleerik/pyplanemode#4] opened 2015-09-06 21:07 UTC
When I set wifi to off in nm-applet PyPlanemode changes it's state to on... don't know if this was the last update?

**Comment by alarangeiras** [comment] 2015-09-07 02:52
Hi,

I analyzed the problem and I realized the cause.
Actualy this script works listing the state of Bluetooth and Wifi devices. If any of them is on it turn it off, and vice versa.
It has a callback that is called each 1000 miliseconds too. When the user turn wi-fi off in the next second the script shows the disabled icon.

I found out two solutions:
1 - We can just remove the callback. In my opinion, this feature is irrelevant to the app.
2 - We can improve the logic that checks the state of these devices. In a few words, it`ll show the disabled icon if only both devices are off.

I can code any solution I mentioned above.

Thanks.

**Comment by lillelilje** [comment] 2015-09-07 07:08
Well, the callback is the only way I found to dynamically update the icon (even if you were to turn off / and "airplane" mode outside of the applet).

Do you have any other ideas to solve that?

If not I agree that the logic should be improved :) 

EDIT: @rudregues the way it works now is rather dirty. It takes the output of rfkill and looks for "yes" (which indicates that some softblock / hardblock is on). However, it does not take anything else into consideration - meaning that the moment one of the senders is off it'll think airplane mode is on.

~~EDIT2:
If we remove the callback the app would be more lightweight - hmm.
What if we implemented both solutions but added a function to manually update the status of the icon? (Or something as strange as on left/rightclick)?~~

Added a related issue: #5

**Comment by oberon-manjaro** [comment] 2015-09-07 10:20
Why not simply switch the icons only when you actually toggle the app? I have the impression that the callback is not really necessary.

**Comment by lillelilje** [comment] 2015-09-07 10:24
That's how it used to work.
The problem is that if someone uses a command to change the status manually the icon will not update. That doesn't feel very "clean" to me.

But, I do agree that it shouldn't be needed. I just don't see another way of making sure the icon is "correct".

**Comment by oberon-manjaro** [comment] 2015-09-07 10:32
Yes, I see your point ... It's both not ideal, yet. Tricky! ;)

**Comment by alarangeiras** [comment] 2015-09-07 10:46
Hi,

I posted a pull request improving the logic to check the status.
Can you check if it solves the problem?

Thanks

**Comment by lillelilje** [comment] 2015-09-07 10:59
That works beautifully. @rudregues could you confirm?

@alarangeiras any ideas regarding the callback discussion?

**Comment by rsmaior** [comment] 2015-09-07 11:47
The issue was fixed for me too!

**Comment by oberon-manjaro** [comment] 2015-09-07 11:51
ok. will bump the package version to 20150907.
BTW does anyone know why I cannot source this with `source=("git://github.com/oleerik/$pkgname")` in the PKGBUILD as I do for other packages?
This gives me `==> ERROR: Cannot find the git package needed to handle git sources.`
Is there maybe anything you can change with your github-account or the settings I wonder?
Meanwhile I can simply git clone manually. But for future updates it would be easier of course... :)

**Comment by lillelilje** [comment] 2015-09-07 12:07
Anything specifically I can check in my settings?

Seems more like it's an issue with dependencies?
https://bugs.archlinux.org/task/43264

**Comment by lillelilje** [comment] 2015-09-07 12:07
Closing this issue as the logic problem is solved.

**Closed as completed by lillelilje** 2015-09-07 12:07 UTC
Labels: bug, enhancement

**Comment by oberon-manjaro** [comment] 2015-09-07 12:15
ah, of course. my stupid mistake ;)

**Comment by alarangeiras** [comment] 2015-09-07 12:49
Hi, @oleerik, about what you asked me of callback discussion:
I see your point about the importance of this callback. I didn't know really well the project and because of that I couldn't realize your intention.
I totally agree about keeping the callback feature, it is very useful. 

Let me know if I can help anything else!

**Comment by lillelilje** [comment] 2015-09-07 13:07
@oberon2007 let me know if I can help at all with the updates!

and thank you @alarangeiras! Very much appreciate your work :)

**Comment by oberon-manjaro** [comment] 2015-09-07 14:48
Thanks @oleerik, no problem. I had deleted my buildenvironment yesterday and forgotten to add makedepends=('git') Therefor the error :)
